version: "3"

services:
  adv-app:
    build: .
    container_name: adv-app
    volumes:
      - ./:/app
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - mysql-db
    command: sh -c "./install.sh"
  mysql-db:
    image: mysql:8
    container_name: mysql-db
    volumes:
      - ./:/mysql
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
